### PR TITLE
enforce forceAll

### LINKED ISSUE #576: Circles 0.21.1 with NC 21.0.1 and Calendar 2.2.0 Results in Calendar App Broken
Like the title says. I upgraded to version 0.21.1 today for the Circles app. I have NC 21.0.1 and Calendar 2.2.0. This results in the calendar being inaccessible from the browser. I cannot see events in the dashboard, and clicking on the calendar results in spinning wheel that never resolves. NextCloud throws errors on every refresh attempt. I could see the calendar still from the Windows app (configured to view NC), but I'm unsure what caching (if any) the Windows app uses.

Downgrading the Circles app to version 0.21.0 corrects this problem.

This should be a cleaned error log from one of the refresh events:
[err.txt](https://github.com/nextcloud/circles/files/6381112/err.txt)

### PR DESCRIPTION
**Pull request by daita**
Should fix #576

### CODE REVIEW

**Review by luckyhandler — APPROVED** [review]

**Comment by luckyhandler** [comment]
I only checked the code and didn't test it.

**Comment by acsfer** [comment]
Not working here. Only reverting https://github.com/nextcloud/circles/pull/566 fixes those issues.

**Comment by Art4** [comment]
Please excuse me if I'm wrong but this PR don't do anything. (I neglect a possible speed advantage)
It just moves the `$forceAll === true` as the first condition in the if-statement.

**Comment by juliushaertl** [comment]
@daita I pushed another commit in order to also pass the forceAll parameter to the method that fetches the members list, which fixes the issue on my test setup.

> Please excuse me if I'm wrong but this PR doesn't do anything. (I neglect a possible speed advantage)
It just moves the $forceAll === true to the first position in the if-condition.

It is not only a speed advantage but due to the OR operation if the first one matches the others will never get evaluated, so the `$circle->getHigherViewer()->isLevel()` which attempted to call on null then would never be executed if forceAll is used. Unfortunately it was only the first half of the fix :wink: 

Anyways testing of the two patches together is highly appreciated.

**Comment by Art4** [comment]
@juliushaertl Thank you for the explanation.

**Comment by armouredking** [comment]
Modifications do not fix for me, see #577 (I can't reopen bug).

**Pull request merged**
