### PR TITLE
Changelog: add NC22 migration notice, fixes #856

### LINKED ISSUE #856: NC 22: Circles migration too slow
We recently upgraded a Nextcloud with a 4 digit number of circles and 5 digit number of users to NC22. After the migration, as documentend in the known issues, the Circle memberships did not work. Just for clarity: that means that many shared files, Decks boards etc are not available for users.

First, we ran

`occ circles:maintenance --level 4`

which is recommended in the known issues section of the forum to facilitate a faster migration of Circles. In our case the command ran for about 3 days and in the end the circles were not migrated.

When looking into the source code, we found that the `circles:sync` command has some parameters that seemingly do what we want:
```
sudo -u www-data php -f /opt/nextcloud/occ circles:sync --migration [--force-run]
```
We're still waiting for the script to finish, but the migration seems to be making visible progress now.

However, the speed is again very limited. Currently, it migrates about 2 memberships per second. The total number of memberships is a 6 digit number.

To sum things up: The speed of the migration is very slow for large Nextcloud installations and the documentation for the problem is lacking. If Circles are widely used in an organization with a large NC installation, then this can be a blocking issue for a migration to NC22.

### PR DESCRIPTION
**Pull request by svenseeberg**
I think it would be prudent to warn admins about the issues with the Circles migration.

### CODE REVIEW

**Comment by ArtificialOwl** [comment]
out of curiosity, how many users/circles do you have for the migration process to take days ?

**Comment by ArtificialOwl** [comment]
also, please sign your commit to fix DCO !

**Comment by svenseeberg** [comment]
We have about 30k users in the Nextcloud and nearly 2k circles.

**Review by ArtificialOwl — APPROVED** [review]

**Comment by svenseeberg** [comment]
Currently, the count is at 194225.

**Comment by svenseeberg** [comment]
I added even more info to the change log. With this info I would be satisfied enough to close the issues #857 & #856.

**Review by ArtificialOwl — APPROVED** [review]

**Pull request merged**
