### PR TITLE
Better 'creation_activity' option handling

### PR DESCRIPTION
**Pull request by tortuetorche**

### CODE REVIEW

**Comment by daita** [comment]
As you saw on #387 the Activity Settings Page now implement a new 'circles_as_non_member' activity feed. 

Now, do we really need to keep the creation_activity option ?

**Comment by daita** [comment]
As you saw on #387 the Activity Settings Page now implement a new 'circles_as_non_member' activity feed. 

Now, do we really need to keep the creation_activity option ?

**Comment by tortuetorche** [comment]
> Now, do we really need to keep the creation_activity option ?

I don't know, I don't use this option, this pull request is just a refactoring of the existing code, to be more readable.

**Pull request merged**
