### PR TITLE
Joined timezone does not consider user timezone #193

### PR DESCRIPTION
**Pull request by fgsl**
- Joined date time is saved using timezone UTC.
- Joined date time is displayed with timezone from user preference (table oc_preferences).

Signed-off-by: Flávio Gomes da Silva Lisboa <flavio.lisboa@serpro.gov.br>

### CODE REVIEW

**Comment by tflidd** [comment]
@MorrisJobke could you take a look at this PR and give a feedback?

**Comment by MorrisJobke** [comment]
cc @daita

**Comment by daita** [comment]
I would have:

- create a Service instead of a Model for the TimeZone class, and not define the unique method as static
- In lib/Db/MembersRequestBuilder.php call the missing Service in the __construct() method instead of creating a new Object of the Application

**Comment by fgsl** [comment]
@daita, it's clear to me about Service instead of Model, but I don't understand the second recommendation. MembersRequestBuilder does not use current TimeZone class. Then I think that I have to inject new service into CirclesRequestBuilder, because its heir CirclesRequest is that uses TimeZone class. Am I right?

**Comment by daita** [comment]
Can you create a branch on this repos instead of cloning on your account, so I can easily work on it ?

**Comment by fgsl** [comment]
Yes, @daita, I can, but I need permissions:

```
remote: Permission to nextcloud/circles.git denied to fgsl.
fatal: unable to access 'https://github.com/nextcloud/circles/': The requested URL returned error: 403
```

**Comment by fgsl** [comment]
Yes, i tried, but for me there is no option "Find or create branch", there is only "Filter branches/tags".

**Comment by MorrisJobke** [comment]
> remote: Permission to nextcloud/circles.git denied to fgsl.
> fatal: unable to access 'https://github.com/nextcloud/circles/': The requested URL returned error: 403

Looks like the config is not correct.



> there is no reason for you to not being able to create a new branch, can you try from the web UI ?

@fgsl is not yet in the community group, so he can only create branches in it's fork.

> Yes, i tried, but for me there is no option "Find or create branch", there is only "Filter branches/tags".

Let me invite you and then use this for the remote:

```
git add remote upstream git@github.com:nextcloud/circles.git
git push upstream BRANCHNAME
```

This then should work.

**Comment by fgsl** [comment]
Great, @MorrisJobke, now it's working! Thank you!

@daita, I created this branch: https://github.com/nextcloud/circles/tree/issue193.

**Comment by daita** [comment]
can you create a new Pull Request using the new branch ?

**Comment by fgsl** [comment]
I sent a new pull request from branch issue193: https://github.com/nextcloud/circles/pull/203

**Pull request closed without merging**
