### PR TITLE
Add Circle hooks

### PR DESCRIPTION
**Pull request by viniciuscb**
This is a proposal for solving #129, add hooks so external applications can listen to circle operations.

Tested in tags/v0.12.4

### CODE REVIEW

**Comment by daita** [comment]
Bom dia @viniciuscb,

Thanks for your contribution, however it seems that the emit/hook system is slightly old and ugly. Can you try to use the EventDispatcher class ?

**Comment by viniciuscb** [comment]
Hi, I will see how we can use EventDispatcher instead of OC_Hook.

**Comment by viniciuscb** [comment]
@daita , Bom dia!

I've just submitted the alteration you have suggested. 

Um abraço!

**Comment by daita** [comment]
Abraco man,

Should created a new branch instead of a fork as I could edit and add the dispatcher in the automatic DI/__construct()

please check https://github.com/nextcloud/circles/commit/a0b31ba7bb3270c7782d501ff710167c481420b5

**Pull request merged**
