### PR TITLE
ignore empty fileIds

### PR DESCRIPTION
**Pull request by ArtificialOwl**
should fix generation of empty AND (()) request

Closes nextcloud/server#46196

### CODE REVIEW

**Comment by brotkastn** [comment]
It may be worth to push this fix with high priority, seeing the files list come back empty is quite scary and might result in lost trust (see #46139 )

**Review by susnux — APPROVED** [review]

**Comment by solracsf** [comment]
Error also present on v28, so target v30 and backport v29 + v28?

**Comment by floss4good** [comment]
If it helps, I tested this fix on Nextcloud 27.1.11 and 29.0.3 and posted my feedback on [server#46196](https://github.com/nextcloud/server/issues/46196).

**Review by joshtrichards — APPROVED** [review]

**Comment by floss4good** [comment]
Are you going to include this fix also in [Nextcloud 27.1.12](https://github.com/nextcloud/circles/milestone/112) milestone or is this app currently released only bundled within Nextcloud server (that has reached EOL for version 27)?

**Comment by joshtrichards** [comment]
It's only released with Server.

**Comment by floss4good** [comment]
Thanks; then I guess you should delete that milestone (# 112).

**Pull request merged**
