### PR TITLE
forceAll in linkedGroups

### LINKED ISSUE #576: Circles 0.21.1 with NC 21.0.1 and Calendar 2.2.0 Results in Calendar App Broken
Like the title says. I upgraded to version 0.21.1 today for the Circles app. I have NC 21.0.1 and Calendar 2.2.0. This results in the calendar being inaccessible from the browser. I cannot see events in the dashboard, and clicking on the calendar results in spinning wheel that never resolves. NextCloud throws errors on every refresh attempt. I could see the calendar still from the Windows app (configured to view NC), but I'm unsure what caching (if any) the Windows app uses.

Downgrading the Circles app to version 0.21.0 corrects this problem.

This should be a cleaned error log from one of the refresh events:
[err.txt](https://github.com/nextcloud/circles/files/6381112/err.txt)

### PR DESCRIPTION
**Pull request by daita**
fix #576

### CODE REVIEW

**Comment by daita** [comment]
@armouredking can you try this one on top of #577 ?

**Comment by armouredking** [comment]
From 0.21.1, I applied #577 and #581. With both I do not get the infinite loading and can access. Calendars are visible from Dashboard widget and from the Calendars browser page. Deck appears to be functional.

We are getting errors still in logs. When visiting the Dashboard with the Calendar event widget, or the Calendars browser page, the following occurs:

```
Error: Use of undefined constant forceAll - assumed 'forceAll' (this will throw an Error in a future version of PHP) at /var/www/nextcloud/apps/circles/lib/Db/MembersRequest.php#516

Error: Use of undefined constant forceAll - assumed 'forceAll' (this will throw an Error in a future version of PHP) at /var/www/nextcloud/apps/circles/lib/Db/MembersRequest.php#516
```

[Sanitized logs attached](https://github.com/nextcloud/circles/files/6421189/err.txt). These errors do not occur when visiting the Deck page.

Notes (just-in-case): We do not use federation (so no testing of that part of Circles), and we recently upgraded to PHP8.

**Pull request merged**
