### PR TITLE
Share to any visible Circle

### PR DESCRIPTION
**Pull request by Shinrai**
See issue #188

### CODE REVIEW

**Comment by daita** [comment]
Hello,

If you want this feature merged, it needs an option in the admin setting page to disable/enable that feature.

**Comment by Shinrai** [comment]
Where is the option to disable/enable sharing to a circle?

**Comment by sunjam** [comment]
@Shinrai Do you need further assistance with understanding how to add an admin toggle for this PR?

**Comment by ArtificialOwl** [comment]
closing as this is out of scope, and pre-22

**Pull request closed without merging**
