### PR TITLE
details on non-visible (but open) circles

### PR DESCRIPTION
**Pull request by ArtificialOwl**
Non-Visible Open Circles should returns details to allow visitor requesting membership

### CODE REVIEW

**Comment by ArtificialOwl** [comment]
This is not the correct behavior and should be backported

**Comment by ArtificialOwl** [comment]
@nextcloud/server-backend please review !

**Review by skjnldsv — APPROVED** [review]

**Review by juliushaertl — APPROVED** [review]
:elephant:

**Pull request merged**
