### PR TITLE
Multiple fixes and add Group Backend support

### PR DESCRIPTION
**Pull request by tortuetorche**
_NOTE: This big pull request will be eventually split in multiple pull requests..._

* Add `group_backend` option to mirroring the circle as a group (automatically suffixed by ` Circle`)
  You can customize prefix and suffix with the `group_backend_name_prefix` and `group_backend_name_suffix` options
  The main goal is to have better integrations with Nextcloud applications and clients. (fix https://github.com/nextcloud/circles/issues/363)
  You should also hide these mirrored circles in Nextcloud applications and clients, because their equivalent group will be used instead, via the `allow_listed_circles` option set to `0`
  * When the `group_backend` option is enabled, store the mirrored group id in the `group_id` column of the `circles_circles` table, useful when the circle's name is updated
  * Add option `allow_listed_circles` To show (`1`, default) or hide (`0`) circles in shared list, disabling this option is very useful when the `group_backend` option is enabled
  * Exclude `personal` and `secret` circles from Group backend, if the `group_backend` option is enabled
* Enhance `onSettingsChange` event to get old setting values (including `name` and `description` attributes).
* Add `allow_adding_any_group_members` option to allow (`1`, default) or not adding group members from any users. When value is set to `0` it's not possible anymore to add contacts as circle members for `private` and `public` circle types, and it's only possible for groups where the current user is a member or for global administrators. Because they can't be group members, useful when the `group_backend` option is enabled. There is already the `accounts_only` option but it applied for any types of circles... (fix https://github.com/nextcloud/circles/issues/128)
* You can now add members in `personal` circles when `skip_invitation_to_closed_circles` option is enabled (fix https://github.com/nextcloud/circles/issues/382 and https://github.com/nextcloud/circles/issues/360)
* Fix Parsing error in activities when user request to join a circle (see https://github.com/nextcloud/circles/issues/243)
* Fix CSS
* Fix translations
* Fix adding group with member limit `-1` or `0` (fix https://github.com/nextcloud/circles/issues/342)

### CODE REVIEW

**Comment by tortuetorche** [comment]
Hi @daita,

Can you tell me if I need to split this big pull request in one pull request per commit, please? 

Have a good day,
Tortue Torche

**Comment by daita** [comment]
Hello,

Thanks for this huge commit, but I would prefer a list of small PR instead ! (also, some of those are already fixed ;p)

Regards,

**Comment by tortuetorche** [comment]
Hi @daita,

> Thanks for this huge commit, but I would prefer a list of small PR instead ! (also, some of those are already fixed ;p)

It's done, here my pull requests: #390, #391, #392, #393, #394, #395, #396, #397, #398, #399, #400 and #401!

NB: You should merge them in the ascendant order, otherwise some issues might appears...

Have a good day,
Tortue Torche

**Comment by joshtrichards** [comment]
Closing since this PR was subsequently handled through split up PRs: https://github.com/nextcloud/circles/pull/384#issuecomment-611456041

**Pull request closed without merging**
